print(" ______________")
print("< Hello, world >")
print(" --------------")
print("        \     ^__^")
print("         \    (oo)\__________")
print("              (__)\          )\/\ ")
print("                  ||------w |    *")
print("                  ||       ||")
print("^"*50)
print("^"*50)
